  # 1/5/24
  # This compose file spins up two Postgres instances - one is a primary and 
  # the other is a read-replica. The Bitnami Postgres Docker images make it
  # super easy! Note that no special SQL scripts are required to GRANT privileges, etc. 
name: hoodoo-postgres-cluster
services:
  postgres-primary:
    image: bitnami/postgresql:15
    environment:
      - POSTGRES_PASSWORD=hoodoo
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_user
      - POSTGRESQL_DATABASE=hoodoo
      - POSTGRESQL_EXTRA_FLAGS=-c wal_level=logical -c max_wal_size=4GB -c min_wal_size=1GB
    expose:
      - 5432
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/var/lib/postgresql/data-hoodoo
  postgres-replica:
    image: bitnami/postgresql:15
    restart: always
    ports:
      - "5434:5432"
    depends_on:
      postgres-primary:
        condition: service_healthy
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=hoodoo
      - POSTGRESQL_MASTER_HOST=postgres-primary
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_user
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    volumes:
      - postgres-replica:/var/lib/postgresql/data-hoodoo
volumes:
  postgres: ~
  postgres-replica: ~
